# Generated by Django 2.0.4 on 2018-07-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_personal_ID', models.CharField(blank=True, max_length=20)),
                ('hostfriendlist', models.TextField(blank=True)),
                ('login_or_not', models.CharField(blank=True, max_length=20)),
                ('requestnumbers', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'Friendlist',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_personal_ID', models.CharField(blank=True, max_length=20)),
                ('guest_personal_ID', models.CharField(blank=True, max_length=20)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Header',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_id', models.IntegerField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_ID', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='RequestCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_personal_ID', models.CharField(blank=True, max_length=20)),
                ('request_ID', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'RequestCheck',
            },
        ),
    ]
