# Generated by Django 2.0.4 on 2018-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_ID', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
    ]
