# Generated by Django 2.0.4 on 2018-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_personal_ID', models.CharField(blank=True, max_length=20)),
                ('guest_personal_ID', models.CharField(blank=True, max_length=20)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Header',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_id', models.IntegerField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
