# Generated by Django 2.0.4 on 2018-07-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180716_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='personal_id',
        ),
        migrations.AddField(
            model_name='personal',
            name='personal_ID',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
