# Generated by Django 2.0.4 on 2018-07-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_header_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_personal_ID', models.CharField(blank=True, max_length=20)),
                ('hostfriendlist', models.TextField(blank=True)),
                ('login_or_not', models.CharField(blank=True, max_length=20)),
                ('friendrequest', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'Friendlist',
            },
        ),
    ]
