# Generated by Django 2.0.4 on 2018-07-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180716_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='requestnumbers',
        ),
    ]
