# Generated by Django 2.0.4 on 2018-07-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180717_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='login_or_not',
        ),
    ]
