# Generated by Django 2.0.4 on 2018-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_friendlist_login_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='hostfriendlist',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
