# Generated by Django 2.0.4 on 2018-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20180721_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='you_guys_chat_room_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
