# Generated by Django 2.0.4 on 2018-07-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20180725_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcheck',
            name='request_ID',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
