# Generated by Django 2.0.4 on 2018-07-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20180725_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='you_guys_chat_room_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='requestcheck',
            name='request_ID',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
