# Generated by Django 2.0.4 on 2018-08-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20180725_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
